
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.compi.compilador;

import com.compi.compilador.NodoFlujo;
import java_cup.runtime.Symbol;
import java.util.ArrayList;
import java.util.List;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\107\000\002\002\004\000\002\002\005\000\002\002" +
    "\003\000\002\021\002\000\002\003\006\000\002\004\004" +
    "\000\002\004\003\000\002\005\004\000\002\005\006\000" +
    "\002\005\005\000\002\005\004\000\002\005\004\000\002" +
    "\005\004\000\002\022\002\000\002\005\012\000\002\023" +
    "\002\000\002\005\012\000\002\006\005\000\002\006\005" +
    "\000\002\006\003\000\002\007\005\000\002\007\005\000" +
    "\002\007\003\000\002\010\003\000\002\010\003\000\002" +
    "\010\003\000\002\010\005\000\002\012\003\000\002\013" +
    "\005\000\002\013\003\000\002\014\005\000\002\014\003" +
    "\000\002\015\004\000\002\015\003\000\002\016\005\000" +
    "\002\016\005\000\002\016\005\000\002\016\005\000\002" +
    "\016\005\000\002\016\005\000\002\017\004\000\002\017" +
    "\003\000\002\020\006\000\002\020\010\000\002\020\010" +
    "\000\002\020\010\000\002\020\010\000\002\020\010\000" +
    "\002\020\010\000\002\020\010\000\002\020\010\000\002" +
    "\020\010\000\002\020\010\000\002\020\010\000\002\020" +
    "\010\000\002\020\010\000\002\020\010\000\002\020\010" +
    "\000\002\011\003\000\002\011\003\000\002\011\003\000" +
    "\002\011\003\000\002\011\003\000\002\011\003\000\002" +
    "\011\003\000\002\011\003\000\002\011\003\000\002\011" +
    "\003\000\002\011\003\000\002\011\003\000\002\011\003" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\255\000\004\004\006\001\002\000\004\002\257\001" +
    "\002\000\006\002\uffff\017\117\001\002\000\016\006\ufffe" +
    "\007\ufffe\012\ufffe\015\ufffe\016\ufffe\075\ufffe\001\002\000" +
    "\016\006\011\007\013\012\017\015\014\016\012\075\010" +
    "\001\002\000\004\035\115\001\002\000\004\075\112\001" +
    "\002\000\004\075\111\001\002\000\004\036\102\001\002" +
    "\000\006\075\100\100\101\001\002\000\024\005\ufffb\006" +
    "\ufffb\007\ufffb\011\ufffb\012\ufffb\014\ufffb\015\ufffb\016\ufffb" +
    "\075\ufffb\001\002\000\020\005\077\006\011\007\013\012" +
    "\017\015\014\016\012\075\010\001\002\000\004\036\020" +
    "\001\002\000\014\030\033\036\021\075\027\076\025\077" +
    "\022\001\002\000\012\036\021\075\027\076\025\077\022" +
    "\001\002\000\060\005\uffe9\006\uffe9\007\uffe9\011\uffe9\012" +
    "\uffe9\014\uffe9\015\uffe9\016\uffe9\020\uffe9\021\uffe9\022\uffe9" +
    "\023\uffe9\024\uffe9\025\uffe9\026\uffe9\027\uffe9\031\uffe9\032" +
    "\uffe9\033\uffe9\034\uffe9\037\uffe9\041\uffe9\075\uffe9\001\002" +
    "\000\010\026\040\027\uffe4\037\uffe4\001\002\000\060\005" +
    "\uffee\006\uffee\007\uffee\011\uffee\012\uffee\014\uffee\015\uffee" +
    "\016\uffee\020\uffee\021\uffee\022\uffee\023\uffee\024\uffee\025" +
    "\uffee\026\uffee\027\uffee\031\uffee\032\uffee\033\066\034\067" +
    "\037\uffee\041\uffee\075\uffee\001\002\000\060\005\uffea\006" +
    "\uffea\007\uffea\011\uffea\012\uffea\014\uffea\015\uffea\016\uffea" +
    "\020\uffea\021\uffea\022\uffea\023\uffea\024\uffea\025\uffea\026" +
    "\uffea\027\uffea\031\uffea\032\uffea\033\uffea\034\uffea\037\uffea" +
    "\041\uffea\075\uffea\001\002\000\022\020\056\021\055\022" +
    "\060\023\057\024\053\025\051\031\054\032\052\001\002" +
    "\000\060\005\uffe8\006\uffe8\007\uffe8\011\uffe8\012\uffe8\014" +
    "\uffe8\015\uffe8\016\uffe8\020\uffe8\021\uffe8\022\uffe8\023\uffe8" +
    "\024\uffe8\025\uffe8\026\uffe8\027\uffe8\031\uffe8\032\uffe8\033" +
    "\uffe8\034\uffe8\037\uffe8\041\uffe8\075\uffe8\001\002\000\060" +
    "\005\uffeb\006\uffeb\007\uffeb\011\uffeb\012\uffeb\014\uffeb\015" +
    "\uffeb\016\uffeb\020\uffeb\021\uffeb\022\uffeb\023\uffeb\024\uffeb" +
    "\025\uffeb\026\uffeb\027\uffeb\031\uffeb\032\uffeb\033\uffeb\034" +
    "\uffeb\037\uffeb\041\uffeb\075\uffeb\001\002\000\004\037\043" +
    "\001\002\000\010\026\uffe0\027\uffe0\037\uffe0\001\002\000" +
    "\014\030\033\036\021\075\027\076\025\077\022\001\002" +
    "\000\010\026\uffe2\027\uffe2\037\uffe2\001\002\000\006\027" +
    "\036\037\uffe6\001\002\000\014\030\033\036\021\075\027" +
    "\076\025\077\022\001\002\000\010\026\040\027\uffe5\037" +
    "\uffe5\001\002\000\014\030\033\036\021\075\027\076\025" +
    "\077\022\001\002\000\010\026\uffe3\027\uffe3\037\uffe3\001" +
    "\002\000\010\026\uffe1\027\uffe1\037\uffe1\001\002\000\004" +
    "\013\044\001\002\000\016\006\ufff2\007\ufff2\012\ufff2\015" +
    "\ufff2\016\ufff2\075\ufff2\001\002\000\016\006\011\007\013" +
    "\012\017\015\014\016\012\075\010\001\002\000\020\006" +
    "\011\007\013\012\017\014\050\015\014\016\012\075\010" +
    "\001\002\000\024\005\ufffc\006\ufffc\007\ufffc\011\ufffc\012" +
    "\ufffc\014\ufffc\015\ufffc\016\ufffc\075\ufffc\001\002\000\024" +
    "\005\ufff1\006\ufff1\007\ufff1\011\ufff1\012\ufff1\014\ufff1\015" +
    "\ufff1\016\ufff1\075\ufff1\001\002\000\012\036\021\075\027" +
    "\076\025\077\022\001\002\000\012\036\021\075\027\076" +
    "\025\077\022\001\002\000\012\036\021\075\027\076\025" +
    "\077\022\001\002\000\012\036\021\075\027\076\025\077" +
    "\022\001\002\000\012\036\021\075\027\076\025\077\022" +
    "\001\002\000\012\036\021\075\027\076\025\077\022\001" +
    "\002\000\012\036\021\075\027\076\025\077\022\001\002" +
    "\000\012\036\021\075\027\076\025\077\022\001\002\000" +
    "\014\026\uffdd\027\uffdd\031\054\032\052\037\uffdd\001\002" +
    "\000\014\026\uffdc\027\uffdc\031\054\032\052\037\uffdc\001" +
    "\002\000\014\026\uffdf\027\uffdf\031\054\032\052\037\uffdf" +
    "\001\002\000\014\026\uffde\027\uffde\031\054\032\052\037" +
    "\uffde\001\002\000\060\005\ufff0\006\ufff0\007\ufff0\011\ufff0" +
    "\012\ufff0\014\ufff0\015\ufff0\016\ufff0\020\ufff0\021\ufff0\022" +
    "\ufff0\023\ufff0\024\ufff0\025\ufff0\026\ufff0\027\ufff0\031\ufff0" +
    "\032\ufff0\033\066\034\067\037\ufff0\041\ufff0\075\ufff0\001" +
    "\002\000\012\036\021\075\027\076\025\077\022\001\002" +
    "\000\012\036\021\075\027\076\025\077\022\001\002\000" +
    "\060\005\uffec\006\uffec\007\uffec\011\uffec\012\uffec\014\uffec" +
    "\015\uffec\016\uffec\020\uffec\021\uffec\022\uffec\023\uffec\024" +
    "\uffec\025\uffec\026\uffec\027\uffec\031\uffec\032\uffec\033\uffec" +
    "\034\uffec\037\uffec\041\uffec\075\uffec\001\002\000\060\005" +
    "\uffed\006\uffed\007\uffed\011\uffed\012\uffed\014\uffed\015\uffed" +
    "\016\uffed\020\uffed\021\uffed\022\uffed\023\uffed\024\uffed\025" +
    "\uffed\026\uffed\027\uffed\031\uffed\032\uffed\033\uffed\034\uffed" +
    "\037\uffed\041\uffed\075\uffed\001\002\000\014\026\uffdb\027" +
    "\uffdb\031\054\032\052\037\uffdb\001\002\000\060\005\uffef" +
    "\006\uffef\007\uffef\011\uffef\012\uffef\014\uffef\015\uffef\016" +
    "\uffef\020\uffef\021\uffef\022\uffef\023\uffef\024\uffef\025\uffef" +
    "\026\uffef\027\uffef\031\uffef\032\uffef\033\066\034\067\037" +
    "\uffef\041\uffef\075\uffef\001\002\000\014\026\uffda\027\uffda" +
    "\031\054\032\052\037\uffda\001\002\000\010\031\054\032" +
    "\052\037\076\001\002\000\060\005\uffe7\006\uffe7\007\uffe7" +
    "\011\uffe7\012\uffe7\014\uffe7\015\uffe7\016\uffe7\020\uffe7\021" +
    "\uffe7\022\uffe7\023\uffe7\024\uffe7\025\uffe7\026\uffe7\027\uffe7" +
    "\031\uffe7\032\uffe7\033\uffe7\034\uffe7\037\uffe7\041\uffe7\075" +
    "\uffe7\001\002\000\006\002\ufffd\017\ufffd\001\002\000\024" +
    "\005\ufff6\006\ufff6\007\ufff6\011\ufff6\012\ufff6\014\ufff6\015" +
    "\ufff6\016\ufff6\075\ufff6\001\002\000\024\005\ufff7\006\ufff7" +
    "\007\ufff7\011\ufff7\012\ufff7\014\ufff7\015\ufff7\016\ufff7\075" +
    "\ufff7\001\002\000\014\030\033\036\021\075\027\076\025" +
    "\077\022\001\002\000\004\037\104\001\002\000\004\010" +
    "\105\001\002\000\016\006\ufff4\007\ufff4\012\ufff4\015\ufff4" +
    "\016\ufff4\075\ufff4\001\002\000\016\006\011\007\013\012" +
    "\017\015\014\016\012\075\010\001\002\000\020\006\011" +
    "\007\013\011\110\012\017\015\014\016\012\075\010\001" +
    "\002\000\024\005\ufff3\006\ufff3\007\ufff3\011\ufff3\012\ufff3" +
    "\014\ufff3\015\ufff3\016\ufff3\075\ufff3\001\002\000\024\005" +
    "\ufff5\006\ufff5\007\ufff5\011\ufff5\012\ufff5\014\ufff5\015\ufff5" +
    "\016\ufff5\075\ufff5\001\002\000\026\005\ufffa\006\ufffa\007" +
    "\ufffa\011\ufffa\012\ufffa\014\ufffa\015\ufffa\016\ufffa\035\113" +
    "\075\ufffa\001\002\000\012\036\021\075\027\076\025\077" +
    "\022\001\002\000\030\005\ufff9\006\ufff9\007\ufff9\011\ufff9" +
    "\012\ufff9\014\ufff9\015\ufff9\016\ufff9\031\054\032\052\075" +
    "\ufff9\001\002\000\012\036\021\075\027\076\025\077\022" +
    "\001\002\000\030\005\ufff8\006\ufff8\007\ufff8\011\ufff8\012" +
    "\ufff8\014\ufff8\015\ufff8\016\ufff8\031\054\032\052\075\ufff8" +
    "\001\002\000\004\042\120\001\002\000\042\055\135\056" +
    "\141\057\136\060\125\061\124\062\140\063\134\064\137" +
    "\065\133\066\142\067\131\070\132\071\143\072\127\073" +
    "\126\074\130\001\002\000\006\002\000\042\120\001\002" +
    "\000\006\002\uffd8\042\uffd8\001\002\000\006\002\uffd9\042" +
    "\uffd9\001\002\000\004\035\253\001\002\000\004\035\247" +
    "\001\002\000\004\035\243\001\002\000\004\035\237\001" +
    "\002\000\004\035\233\001\002\000\004\035\227\001\002" +
    "\000\004\035\223\001\002\000\004\035\217\001\002\000" +
    "\004\035\213\001\002\000\004\035\211\001\002\000\004" +
    "\035\205\001\002\000\004\035\201\001\002\000\004\035" +
    "\175\001\002\000\004\035\171\001\002\000\004\035\165" +
    "\001\002\000\004\035\144\001\002\000\042\036\021\043" +
    "\153\044\156\045\161\046\162\047\155\050\160\051\147" +
    "\052\154\053\151\054\145\075\027\076\025\077\022\101" +
    "\152\102\146\001\002\000\004\041\uffbb\001\002\000\004" +
    "\041\uffc6\001\002\000\004\041\uffbe\001\002\000\010\031" +
    "\054\032\052\041\uffc7\001\002\000\004\041\uffbc\001\002" +
    "\000\004\041\uffc5\001\002\000\004\041\uffc4\001\002\000" +
    "\004\041\uffbd\001\002\000\004\041\uffc0\001\002\000\004" +
    "\041\uffc3\001\002\000\004\041\163\001\002\000\004\041" +
    "\uffbf\001\002\000\004\041\uffc2\001\002\000\004\041\uffc1" +
    "\001\002\000\004\076\164\001\002\000\006\002\uffcb\042" +
    "\uffcb\001\002\000\042\036\021\043\153\044\156\045\161" +
    "\046\162\047\155\050\160\051\147\052\154\053\151\054" +
    "\145\075\027\076\025\077\022\101\152\102\146\001\002" +
    "\000\004\041\167\001\002\000\004\076\170\001\002\000" +
    "\006\002\uffce\042\uffce\001\002\000\042\036\021\043\153" +
    "\044\156\045\161\046\162\047\155\050\160\051\147\052" +
    "\154\053\151\054\145\075\027\076\025\077\022\101\152" +
    "\102\146\001\002\000\004\041\173\001\002\000\004\076" +
    "\174\001\002\000\006\002\uffd6\042\uffd6\001\002\000\042" +
    "\036\021\043\153\044\156\045\161\046\162\047\155\050" +
    "\160\051\147\052\154\053\151\054\145\075\027\076\025" +
    "\077\022\101\152\102\146\001\002\000\004\041\177\001" +
    "\002\000\004\076\200\001\002\000\006\002\uffd2\042\uffd2" +
    "\001\002\000\042\036\021\043\153\044\156\045\161\046" +
    "\162\047\155\050\160\051\147\052\154\053\151\054\145" +
    "\075\027\076\025\077\022\101\152\102\146\001\002\000" +
    "\004\041\203\001\002\000\004\076\204\001\002\000\006" +
    "\002\uffd0\042\uffd0\001\002\000\042\036\021\043\153\044" +
    "\156\045\161\046\162\047\155\050\160\051\147\052\154" +
    "\053\151\054\145\075\027\076\025\077\022\101\152\102" +
    "\146\001\002\000\004\041\207\001\002\000\004\076\210" +
    "\001\002\000\006\002\uffd5\042\uffd5\001\002\000\004\076" +
    "\212\001\002\000\006\002\uffd7\042\uffd7\001\002\000\042" +
    "\036\021\043\153\044\156\045\161\046\162\047\155\050" +
    "\160\051\147\052\154\053\151\054\145\075\027\076\025" +
    "\077\022\101\152\102\146\001\002\000\004\041\215\001" +
    "\002\000\004\076\216\001\002\000\006\002\uffd1\042\uffd1" +
    "\001\002\000\042\036\021\043\153\044\156\045\161\046" +
    "\162\047\155\050\160\051\147\052\154\053\151\054\145" +
    "\075\027\076\025\077\022\101\152\102\146\001\002\000" +
    "\004\041\221\001\002\000\004\076\222\001\002\000\006" +
    "\002\uffcf\042\uffcf\001\002\000\042\036\021\043\153\044" +
    "\156\045\161\046\162\047\155\050\160\051\147\052\154" +
    "\053\151\054\145\075\027\076\025\077\022\101\152\102" +
    "\146\001\002\000\004\041\225\001\002\000\004\076\226" +
    "\001\002\000\006\002\uffcc\042\uffcc\001\002\000\042\036" +
    "\021\043\153\044\156\045\161\046\162\047\155\050\160" +
    "\051\147\052\154\053\151\054\145\075\027\076\025\077" +
    "\022\101\152\102\146\001\002\000\004\041\231\001\002" +
    "\000\004\076\232\001\002\000\006\002\uffcd\042\uffcd\001" +
    "\002\000\042\036\021\043\153\044\156\045\161\046\162" +
    "\047\155\050\160\051\147\052\154\053\151\054\145\075" +
    "\027\076\025\077\022\101\152\102\146\001\002\000\004" +
    "\041\235\001\002\000\004\076\236\001\002\000\006\002" +
    "\uffc8\042\uffc8\001\002\000\042\036\021\043\153\044\156" +
    "\045\161\046\162\047\155\050\160\051\147\052\154\053" +
    "\151\054\145\075\027\076\025\077\022\101\152\102\146" +
    "\001\002\000\004\041\241\001\002\000\004\076\242\001" +
    "\002\000\006\002\uffca\042\uffca\001\002\000\042\036\021" +
    "\043\153\044\156\045\161\046\162\047\155\050\160\051" +
    "\147\052\154\053\151\054\145\075\027\076\025\077\022" +
    "\101\152\102\146\001\002\000\004\041\245\001\002\000" +
    "\004\076\246\001\002\000\006\002\uffc9\042\uffc9\001\002" +
    "\000\042\036\021\043\153\044\156\045\161\046\162\047" +
    "\155\050\160\051\147\052\154\053\151\054\145\075\027" +
    "\076\025\077\022\101\152\102\146\001\002\000\004\041" +
    "\251\001\002\000\004\076\252\001\002\000\006\002\uffd4" +
    "\042\uffd4\001\002\000\042\036\021\043\153\044\156\045" +
    "\161\046\162\047\155\050\160\051\147\052\154\053\151" +
    "\054\145\075\027\076\025\077\022\101\152\102\146\001" +
    "\002\000\004\041\255\001\002\000\004\076\256\001\002" +
    "\000\006\002\uffd3\042\uffd3\001\002\000\004\002\001\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\255\000\006\002\003\003\004\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\021\006\001\001\000\006" +
    "\004\015\005\014\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\005\046\001\001\000\002\001" +
    "\001\000\022\006\025\007\023\010\027\012\030\013\034" +
    "\014\022\015\033\016\031\001\001\000\010\006\074\007" +
    "\023\010\027\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\014\006\025\007\023\010\027\015\041\016" +
    "\031\001\001\000\002\001\001\000\002\001\001\000\016" +
    "\006\025\007\023\010\027\014\036\015\033\016\031\001" +
    "\001\000\002\001\001\000\014\006\025\007\023\010\027" +
    "\015\040\016\031\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\023\044\001\001\000\006" +
    "\004\045\005\014\001\001\000\004\005\046\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\006\073\007\023" +
    "\010\027\001\001\000\006\007\072\010\027\001\001\000" +
    "\010\006\071\007\023\010\027\001\001\000\006\007\064" +
    "\010\027\001\001\000\010\006\063\007\023\010\027\001" +
    "\001\000\010\006\062\007\023\010\027\001\001\000\010" +
    "\006\061\007\023\010\027\001\001\000\010\006\060\007" +
    "\023\010\027\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\010\070\001\001\000\004\010\067\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\022\006\025\007\023\010\027\012\102\013\034\014\022" +
    "\015\033\016\031\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\022\105\001\001\000\006\004\106\005\014" +
    "\001\001\000\004\005\046\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\006\113\007\023" +
    "\010\027\001\001\000\002\001\001\000\010\006\115\007" +
    "\023\010\027\001\001\000\002\001\001\000\006\017\120" +
    "\020\121\001\001\000\002\001\001\000\004\020\122\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\012\006\147\007" +
    "\023\010\027\011\156\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\012\006\147\007\023\010" +
    "\027\011\165\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\012\006\147\007\023\010\027\011" +
    "\171\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\012\006\147\007\023\010\027\011\175\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\012\006\147\007\023\010\027\011\201\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\012" +
    "\006\147\007\023\010\027\011\205\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\012\006\147\007\023\010\027\011" +
    "\213\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\012\006\147\007\023\010\027\011\217\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\012\006\147\007\023\010\027\011\223\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\012" +
    "\006\147\007\023\010\027\011\227\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\006\147" +
    "\007\023\010\027\011\233\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\012\006\147\007\023" +
    "\010\027\011\237\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\006\147\007\023\010\027" +
    "\011\243\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\006\147\007\023\010\027\011\247" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\012\006\147\007\023\010\027\011\253\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    /* ====== LISTAS ====== */

    private List<String> syntaxErrors = new ArrayList<>();
    private List<NodoFlujo> nodos = new ArrayList<>();

    private int contadorIndice = 1;

    public List<String> getSyntaxErrors(){
        return syntaxErrors;
    }

    public List<NodoFlujo> getNodos(){
        return nodos;
    }

    /* ====== ERRORES ====== */

    @Override
    public void syntax_error(Symbol s) {
        syntaxErrors.add(
            "Error Sintáctico Línea: " + s.left +
            " Columna: " + s.right
        );
    }

    @Override
    public void unrecovered_syntax_error(Symbol s){
        syntaxErrors.add("Error irrecuperable");
    }

    /* ====== APLICAR CONFIG ====== */
    private void aplicarConfig(String instruccion, Object valorObj, int indice){

        if(valorObj == null) return;

        String valor = valorObj.toString();

        for(NodoFlujo nodo : nodos){

            if(indice != -1 && nodo.indice != indice)
                continue;

            switch(instruccion){

                // ================= DEFAULT =================
                case "DEFAULT":
                    nodo.figura = "RECTANGULO";
                    nodo.colorFondo = "#FFFFFF";
                    nodo.colorTexto = "#000000";
                    nodo.fuente = "ARIAL";
                    nodo.tamañoLetra = 14;
                    break;

                // ================= SI =================
                case "COLOR_TEXTO_SI":
                    if(nodo.tipo.equals("SI"))
                        nodo.colorTexto = procesarColor(valor);
                    break;

                case "COLOR_SI":
                    if(nodo.tipo.equals("SI"))
                        nodo.colorFondo = procesarColor(valor);
                    break;

                case "FIGURA_SI":
                    if(nodo.tipo.equals("SI"))
                        nodo.figura = valor;
                    break;

                case "LETRA_SI":
                    if(nodo.tipo.equals("SI"))
                        nodo.fuente = valor;
                    break;

                case "LETRA_SIZE_SI":
                    if(nodo.tipo.equals("SI"))
                        nodo.tamañoLetra = (float) evaluar(valor);
                    break;

                // ================= MIENTRAS =================
                case "COLOR_TEXTO_MIENTRAS":
                    if(nodo.tipo.equals("MIENTRAS"))
                        nodo.colorTexto = procesarColor(valor);
                    break;

                case "COLOR_MIENTRAS":
                    if(nodo.tipo.equals("MIENTRAS"))
                        nodo.colorFondo = procesarColor(valor);
                    break;

                case "FIGURA_MIENTRAS":
                    if(nodo.tipo.equals("MIENTRAS"))
                        nodo.figura = valor;
                    break;

                case "LETRA_MIENTRAS":
                    if(nodo.tipo.equals("MIENTRAS"))
                        nodo.fuente = valor;
                    break;

                case "LETRA_SIZE_MIENTRAS":
                    if(nodo.tipo.equals("MIENTRAS"))
                        nodo.tamañoLetra = (float) evaluar(valor);
                    break;
            }
        }
    }

    private String procesarColor(String valor){

        // Si es RGB
        if(valor.contains(",")){

            String[] partes = valor.split(",");

            if(partes.length == 3){

                double r = evaluar(partes[0]);
                double g = evaluar(partes[1]);
                double b = evaluar(partes[2]);

                r = Math.max(0, Math.min(255, r));
                g = Math.max(0, Math.min(255, g));
                b = Math.max(0, Math.min(255, b));

                int ri = (int) r;
                int gi = (int) g;
                int bi = (int) b;

                // Convertir a HEX Android (#RRGGBB)
                return String.format("#%02X%02X%02X", ri, gi, bi);
            }
        }

        // Si es HEX tipo HFFFFFF → convertirlo a #FFFFFF
        if(valor.startsWith("H")){
            return "#" + valor.substring(1);
        }

        // Si ya viene como #FFFFFF
        if(valor.startsWith("#")){
            return valor;
        }

        return "#FFFFFF"; // color por defecto seguro
    }
    private double evaluar(String expr) {
        try {
            return evaluarExpresion(expr.replaceAll("\\s+", ""));
        } catch (Exception e) {
            System.out.println("Error evaluando: " + expr);
            return 0;
        }
    }
    private double evaluarExpresion(String expr) {

        if (expr.contains("+")) {
            String[] partes = expr.split("\\+", 2);
            return evaluarExpresion(partes[0]) + evaluarExpresion(partes[1]);
        }

        if (expr.contains("-")) {
            int index = expr.lastIndexOf("-");
            if (index > 0) {
                return evaluarExpresion(expr.substring(0, index))
                        - evaluarExpresion(expr.substring(index + 1));
            }
        }

        if (expr.contains("*")) {
            String[] partes = expr.split("\\*", 2);
            return evaluarExpresion(partes[0]) * evaluarExpresion(partes[1]);
        }

        if (expr.contains("/")) {
            String[] partes = expr.split("/", 2);
            return evaluarExpresion(partes[0]) / evaluarExpresion(partes[1]);
        }

        return Double.parseDouble(expr);
    }
    

/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= seccion_algoritmo SEPARADOR seccion_config 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // programa ::= seccion_algoritmo 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // NT$0 ::= 
            {
              Object RESULT =null;
		int Ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int Iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object I = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
 nodos.add(new NodoFlujo("INICIO","INICIO",contadorIndice++));
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$0",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // seccion_algoritmo ::= INICIO NT$0 bloque FIN 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int Ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int Iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Object I = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int Fleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int Fright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object F = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 nodos.add(new NodoFlujo("FIN","FIN",contadorIndice++));
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("seccion_algoritmo",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // bloque ::= bloque instruccion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // bloque ::= instruccion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // instruccion ::= VAR ID 
            {
              Object RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
               nodos.add(new NodoFlujo("PROCESO",
                   "VAR " + i,
                   contadorIndice++
               ));
            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // instruccion ::= VAR ID ASIGNACION expresion 
            {
              Object RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
               nodos.add(new NodoFlujo("PROCESO",
                   "VAR " + i + " = " + e,
                   contadorIndice++
               ));
            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // instruccion ::= ID ASIGNACION expresion 
            {
              Object RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
               nodos.add(new NodoFlujo("PROCESO",
                   i + " = " + e,
                   contadorIndice++
               ));
            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // instruccion ::= MOSTRAR STRING 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 nodos.add(new NodoFlujo("SALIDA",
           "MOSTRAR " + s,
           contadorIndice++
        )); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // instruccion ::= MOSTRAR ID 
            {
              Object RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 nodos.add(new NodoFlujo("SALIDA",
           "MOSTRAR " + i,
           contadorIndice++
        )); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // instruccion ::= LEER ID 
            {
              Object RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 nodos.add(new NodoFlujo("ENTRADA",
           "LEER " + i,
           contadorIndice++
        )); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // NT$1 ::= 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
 
               Symbol symS = (Symbol) s; 
               String cond = c.toString();
               nodos.add(new NodoFlujo(
                   "SI",
                   "(" + cond + ")",
                   contadorIndice++
               ));
            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$1",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // instruccion ::= SI PAR_A condicion PAR_C ENTONCES NT$1 bloque FINSI 
            {
              Object RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		Object s = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		
               Symbol symS = (Symbol) s;
               nodos.add(new NodoFlujo(
                   "FIN_SI",
                   "",
                   contadorIndice++
               ));
            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // NT$2 ::= 
            {
              Object RESULT =null;
		int mleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int mright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		Object m = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;

               Symbol symM = (Symbol) m;
               String cond = c.toString();
               nodos.add(new NodoFlujo(
                   "MIENTRAS",
                   "(" + cond + ")",
                   contadorIndice++
               ));
            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$2",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // instruccion ::= MIENTRAS PAR_A condicion PAR_C HACER NT$2 bloque FINMIENTRAS 
            {
              Object RESULT =null;
              // propagate RESULT from NT$2
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int mleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int mright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		Object m = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		
               Symbol symM = (Symbol) m;
               nodos.add(new NodoFlujo(
                   "FIN_MIENTRAS",
                   "",
                   contadorIndice++
               ));
            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // expresion ::= expresion SUMA termino 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1.toString() + "+" + e2.toString(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // expresion ::= expresion RESTA termino 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1.toString() + "-" + e2.toString(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // expresion ::= termino 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = t; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // termino ::= termino MULTIPLICACION factor 
            {
              Object RESULT =null;
		int t1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int t1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object t1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object f = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = t1.toString() + "*" + f.toString(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("termino",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // termino ::= termino DIVISION factor 
            {
              Object RESULT =null;
		int t1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int t1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object t1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object f = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = t1.toString() + "/" + f.toString(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("termino",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // termino ::= factor 
            {
              Object RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object f = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = f; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("termino",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // factor ::= ENTERO 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // factor ::= DECIMAL 
            {
              Object RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String d = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = d; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // factor ::= ID 
            {
              Object RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = i; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // factor ::= PAR_A expresion PAR_C 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // condicion ::= condicion_or 
            {
              Object RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = c; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // condicion_or ::= condicion_or OR condicion_and 
            {
              Object RESULT =null;
		int c1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int c1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object c1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int c2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int c2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object c2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = c1 + " OR " + c2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion_or",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // condicion_or ::= condicion_and 
            {
              Object RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = c; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion_or",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // condicion_and ::= condicion_and AND condicion_not 
            {
              Object RESULT =null;
		int c1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int c1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object c1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int c2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int c2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object c2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = c1 + " AND " + c2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion_and",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // condicion_and ::= condicion_not 
            {
              Object RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = c; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion_and",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // condicion_not ::= NOT condicion_not 
            {
              Object RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = "NOT " + c; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion_not",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // condicion_not ::= condicion_base 
            {
              Object RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = c; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion_not",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // condicion_base ::= expresion IGUALDAD expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1 + " == " + e2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion_base",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // condicion_base ::= expresion DIFERENTE expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1 + " != " + e2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion_base",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // condicion_base ::= expresion MAYOR expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1 + " > " + e2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion_base",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // condicion_base ::= expresion MENOR expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1 + " < " + e2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion_base",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // condicion_base ::= expresion MAYORIGUAL expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1 + " >= " + e2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion_base",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // condicion_base ::= expresion MENORIGUAL expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e1 + " <= " + e2; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion_base",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // seccion_config ::= seccion_config instruccion_config 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("seccion_config",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // seccion_config ::= instruccion_config 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("seccion_config",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // instruccion_config ::= PORCENTAJE DEFAULT ASIGNACION ENTERO 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 aplicarConfig("DEFAULT", e, Integer.parseInt(e.toString())); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // instruccion_config ::= PORCENTAJE COLOR_TEXTO_SI ASIGNACION valor_config PIPE ENTERO 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 aplicarConfig("COLOR_TEXTO_SI", v, Integer.parseInt(e.toString())); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // instruccion_config ::= PORCENTAJE COLOR_SI ASIGNACION valor_config PIPE ENTERO 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 aplicarConfig("COLOR_SI", v, Integer.parseInt(e.toString())); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // instruccion_config ::= PORCENTAJE FIGURA_SI ASIGNACION valor_config PIPE ENTERO 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 aplicarConfig("FIGURA_SI", v, Integer.parseInt(e.toString())); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // instruccion_config ::= PORCENTAJE LETRA_SI ASIGNACION valor_config PIPE ENTERO 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 aplicarConfig("LETRA_SI", v, Integer.parseInt(e.toString())); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // instruccion_config ::= PORCENTAJE LETRA_SIZE_SI ASIGNACION valor_config PIPE ENTERO 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 aplicarConfig("LETRA_SIZE_SI", v, Integer.parseInt(e.toString())); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // instruccion_config ::= PORCENTAJE COLOR_TEXTO_MIENTRAS ASIGNACION valor_config PIPE ENTERO 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 aplicarConfig("COLOR_TEXTO_MIENTRAS", v, Integer.parseInt(e.toString())); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // instruccion_config ::= PORCENTAJE COLOR_MIENTRAS ASIGNACION valor_config PIPE ENTERO 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 aplicarConfig("COLOR_MIENTRAS", v, Integer.parseInt(e.toString())); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // instruccion_config ::= PORCENTAJE FIGURA_MIENTRAS ASIGNACION valor_config PIPE ENTERO 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 aplicarConfig("FIGURA_MIENTRAS", v, Integer.parseInt(e.toString())); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // instruccion_config ::= PORCENTAJE LETRA_MIENTRAS ASIGNACION valor_config PIPE ENTERO 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 aplicarConfig("LETRA_MIENTRAS", v, Integer.parseInt(e.toString())); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // instruccion_config ::= PORCENTAJE LETRA_SIZE_MIENTRAS ASIGNACION valor_config PIPE ENTERO 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 aplicarConfig("LETRA_SIZE_MIENTRAS", v, Integer.parseInt(e.toString())); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // instruccion_config ::= PORCENTAJE COLOR_TEXTO_BLOQUE ASIGNACION valor_config PIPE ENTERO 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 aplicarConfig("COLOR_TEXTO_BLOQUE", v, Integer.parseInt(e.toString())); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // instruccion_config ::= PORCENTAJE COLOR_BLOQUE ASIGNACION valor_config PIPE ENTERO 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 aplicarConfig("COLOR_BLOQUE", v, Integer.parseInt(e.toString())); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // instruccion_config ::= PORCENTAJE FIGURA_BLOQUE ASIGNACION valor_config PIPE ENTERO 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 aplicarConfig("FIGURA_BLOQUE", v, Integer.parseInt(e.toString())); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // instruccion_config ::= PORCENTAJE LETRA_BLOQUE ASIGNACION valor_config PIPE ENTERO 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 aplicarConfig("LETRA_BLOQUE", v, Integer.parseInt(e.toString())); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // instruccion_config ::= PORCENTAJE LETRA_SIZE_BLOQUE ASIGNACION valor_config PIPE ENTERO 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object v = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 aplicarConfig("LETRA_SIZE_BLOQUE", v, Integer.parseInt(e.toString())); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion_config",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // valor_config ::= expresion 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor_config",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // valor_config ::= RGB 
            {
              Object RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int rright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object r = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = r; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor_config",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // valor_config ::= HEX 
            {
              Object RESULT =null;
		int hleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int hright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object h = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = h; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor_config",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // valor_config ::= ELIPSE 
            {
              Object RESULT =null;
		 RESULT = "ELIPSE"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor_config",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // valor_config ::= CIRCULO 
            {
              Object RESULT =null;
		 RESULT = "CIRCULO"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor_config",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // valor_config ::= PARALELOGRAMO 
            {
              Object RESULT =null;
		 RESULT = "PARALELOGRAMO"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor_config",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // valor_config ::= RECTANGULO 
            {
              Object RESULT =null;
		 RESULT = "RECTANGULO"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor_config",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // valor_config ::= ROMBO 
            {
              Object RESULT =null;
		 RESULT = "ROMBO"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor_config",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // valor_config ::= RECTANGULO_REDONDEADO 
            {
              Object RESULT =null;
		 RESULT = "RECTANGULO_REDONDEADO"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor_config",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // valor_config ::= ARIAL 
            {
              Object RESULT =null;
		 RESULT = "ARIAL"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor_config",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // valor_config ::= TIMES_NEW_ROMAN 
            {
              Object RESULT =null;
		 RESULT = "TIMES_NEW_ROMAN"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor_config",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // valor_config ::= COMIC_SANS 
            {
              Object RESULT =null;
		 RESULT = "COMIC_SANS"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor_config",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // valor_config ::= VERDANA 
            {
              Object RESULT =null;
		 RESULT = "VERDANA"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("valor_config",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
