
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.compi.compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COLOR_TEXTO_BLOQUE = 54;
  public static final int LETRA_SIZE_MIENTRAS = 53;
  public static final int ENTERO = 60;
  public static final int SI = 5;
  public static final int MOSTRAR = 11;
  public static final int FIGURA_BLOQUE = 56;
  public static final int DIFERENTE = 15;
  public static final int RESTA = 24;
  public static final int LETRA_MIENTRAS = 52;
  public static final int PORCENTAJE = 32;
  public static final int ENTONCES = 6;
  public static final int HEX = 63;
  public static final int RECTANGULO_REDONDEADO = 38;
  public static final int SEPARADOR = 13;
  public static final int FIN = 3;
  public static final int NOT = 22;
  public static final int MENORIGUAL = 19;
  public static final int AND = 20;
  public static final int FINMIENTRAS = 10;
  public static final int IGUALDAD = 14;
  public static final int OR = 21;
  public static final int MIENTRAS = 8;
  public static final int LETRA_SIZE_BLOQUE = 58;
  public static final int ARIAL = 39;
  public static final int CIRCULO = 34;
  public static final int SUMA = 23;
  public static final int ID = 59;
  public static final int MAYORIGUAL = 18;
  public static final int DECIMAL = 61;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COLOR_BLOQUE = 55;
  public static final int COMA = 30;
  public static final int COMIC_SANS = 41;
  public static final int PIPE = 31;
  public static final int COLOR_MIENTRAS = 50;
  public static final int MENOR = 17;
  public static final int COLOR_TEXTO_MIENTRAS = 49;
  public static final int PAR_C = 29;
  public static final int PAR_A = 28;
  public static final int VERDANA = 42;
  public static final int RGB = 64;
  public static final int LETRA_BLOQUE = 57;
  public static final int TIMES_NEW_ROMAN = 40;
  public static final int ASIGNACION = 27;
  public static final int MAYOR = 16;
  public static final int ELIPSE = 33;
  public static final int ROMBO = 37;
  public static final int RECTANGULO = 36;
  public static final int FIGURA_MIENTRAS = 51;
  public static final int DEFAULT = 43;
  public static final int LEER = 12;
  public static final int HACER = 9;
  public static final int STRING = 62;
  public static final int LETRA_SI = 47;
  public static final int COLOR_SI = 45;
  public static final int PARALELOGRAMO = 35;
  public static final int INICIO = 2;
  public static final int FINSI = 7;
  public static final int DIVISION = 26;
  public static final int COLOR_TEXTO_SI = 44;
  public static final int FIGURA_SI = 46;
  public static final int VAR = 4;
  public static final int MULTIPLICACION = 25;
  public static final int LETRA_SIZE_SI = 48;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INICIO",
  "FIN",
  "VAR",
  "SI",
  "ENTONCES",
  "FINSI",
  "MIENTRAS",
  "HACER",
  "FINMIENTRAS",
  "MOSTRAR",
  "LEER",
  "SEPARADOR",
  "IGUALDAD",
  "DIFERENTE",
  "MAYOR",
  "MENOR",
  "MAYORIGUAL",
  "MENORIGUAL",
  "AND",
  "OR",
  "NOT",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "ASIGNACION",
  "PAR_A",
  "PAR_C",
  "COMA",
  "PIPE",
  "PORCENTAJE",
  "ELIPSE",
  "CIRCULO",
  "PARALELOGRAMO",
  "RECTANGULO",
  "ROMBO",
  "RECTANGULO_REDONDEADO",
  "ARIAL",
  "TIMES_NEW_ROMAN",
  "COMIC_SANS",
  "VERDANA",
  "DEFAULT",
  "COLOR_TEXTO_SI",
  "COLOR_SI",
  "FIGURA_SI",
  "LETRA_SI",
  "LETRA_SIZE_SI",
  "COLOR_TEXTO_MIENTRAS",
  "COLOR_MIENTRAS",
  "FIGURA_MIENTRAS",
  "LETRA_MIENTRAS",
  "LETRA_SIZE_MIENTRAS",
  "COLOR_TEXTO_BLOQUE",
  "COLOR_BLOQUE",
  "FIGURA_BLOQUE",
  "LETRA_BLOQUE",
  "LETRA_SIZE_BLOQUE",
  "ID",
  "ENTERO",
  "DECIMAL",
  "STRING",
  "HEX",
  "RGB"
  };
}

